DefaultContentLanguage: en
languageCode: "en-us"
canonifyURLs: true
baseURL: https://icon.community/

title: "ICON Community"
description: "ICON is a public blockchain protocol building a hyperconnected future with BTP, a chain-agnostic interoperability solution."

permalinks:
  post: :slug/
  page: :slug/

sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5

categories:
  - announcements
  - community
  - ecosystem
  - events
  - opinion
  - technology
  - tutorial

params:
  authors:
    sudoblock:
      name: "Sudoblock"
      description: "Sudoblock is a big infrastructure partner and validator on the ICON Network. Blockchain indexing and infrastructure is the Sudeblock core business."
      validatorAddress: "hxfc56203484921c3b7a4dee9579d8614d8c8daaf5"
    cyrus:
      name: "Cyrus"
      description: ""
      validatorAddress: ""
    venture-23:
      name: "Venture23"
      description: ""
      validatorAddress: ""
    eye-on-icon:
      name: "Eye on ICON"
      description: "Eye on ICON is a community podcast and validator. The Eye on ICON podcast goes around the ICON ecosystem and brings you all the latest news, chatter and alpha."
      validatorAddress: "hx2e7db537ca3ff73336bee1bab4cf733a94ae769b"
    espanicon:
      name: "Espanicon"
      description: "Espanicon is a validator on the ICON network. Their goal is to participate in the chain governance of the network and expand the ICON ecosystem by building projects in it and collaborating with other validators."
      validatorAddress: "hx9fa9d224306b0722099d30471b3c2306421aead7"
    icon-foundation:
      name: "ICON Foundation"
      description:
    rhizome-labs:
      name: "RHIZOME Labs"
      description: "RHIZOME Labs is a longtime contributor to the ICON blockchain. In addition to operating a validator node, RHIZOME Labs also develops various ICON-related tools and dashboards (e.g. RHIZOME Tracker and icon.community), publishes blog posts and tutorials, and more."
      validatorAddress: "hx4a43790d44b07909d20fbcc233548fc80f7a4067"
  banner:
    message:
    url:
  featuredPostUrl: what-is-the-icx-token
  forms:
    faqSubmissionUrl: /icondiscord/
    ecosystemSubmissionUrl: https://se8br1ugut6.typeform.com/to/MBBDnTNG
    incentiveProgramSubmissionUrl: https://forms.gle/yTFDdMMDHL8bhsNF7
  social:
    discordUrl: /icondiscord/
    githubUrl: https://github.com/icon-project
    newsletterUrl: https://newsletter.icon.community/
    roadmapUrl: https://iconfoundation.notion.site/BTP-Milestones-78dbe0023a0144ba9c53db9558ac7cf5
    twitterUrl: https://twitter.com/helloiconworld
  
markup:
  tableOfContents:
    endLevel: 2